[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Lock the Solidity compiler version to 0.8.30
solc = "0.8.30"
# Enable the optimizer
optimizer = true
optimizer_runs = 200
# Ensure deterministic init code hash
bytecode_hash = "none"
# Remappings
remappings = ["forge-std/=lib/forge-std/src/"]

[lint]
lint_on_build = false
exclude_lints = ["screaming-snake-case-immutable", "unwrapped-modifier-logic"]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "http://localhost:8545"
anvil = "http://localhost:8545"
# anvil-hardhat = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# Disable verification for local chains
# localhost = { key = "dummy", url = "http://localhost:8545" }
# anvil = { key = "dummy", url = "http://localhost:8545" }
# anvil-hardhat = { key = "dummy", url = "http://localhost:8545" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
